# This is a basic workflow that is manually triggered

name: Release library (-kotlinx-datetime)

on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          gpg-private-key: ${{ secrets.GPG_SIGNING_KEY }} 
          gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }}
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v3
      - name: Publish package
        uses: gradle/gradle-build-action@v3
        with:
          arguments: :JpNHolidayK-kotlinx-datetime:publishMavenJavaPublicationToMavenRepository
        env:
          sonatype_username: ${{ secrets.SONATYPE_USERNAME }}
          sonatype_password: ${{ secrets.SONATYPE_PASSWORD }}
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.ORG_GRADLE_PROJECT_signingKey }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.ORG_GRADLE_PROJECT_signingPassword }}
